let en_food = [
  {
    Name: "Apricots",
    Proteins: 1,
    Fat: 0,
    Carbohydrates: 10,
    Calorie: 45,
  },
  {
    Name: "Avocado",
    Proteins: 2,
    Fat: 19,
    Carbohydrates: 7,
    Calorie: 197,
  },
  {
    Name: "Adzhika",
    Proteins: 2,
    Fat: 3,
    Carbohydrates: 8,
    Calorie: 59,
  },
  {
    Name: "Quince",
    Proteins: 1,
    Fat: 0,
    Carbohydrates: 9,
    Calorie: 41,
  },
  {
    Name: "Iceberg",
    Proteins: 1,
    Fat: 0,
    Carbohydrates: 2,
    Calorie: 17,
  },
  {
    Name: "A pineapple",
    Proteins: 0,
    Fat: 0,
    Carbohydrates: 12,
    Calorie: 50,
  },
  {
    Name: "Pineapple is canned",
    Proteins: 0,
    Fat: 0,
    Carbohydrates: 16,
    Calorie: 65,
  },
  {
    Name: "Pineapple tsukatas",
    Proteins: 1,
    Fat: 2,
    Carbohydrates: 15,
    Calorie: 78,
  },
  {
    Name: "Orange",
    Proteins: 2,
    Fat: 0,
    Carbohydrates: 9,
    Calorie: 43,
  },
  {
    Name: "Orange juice",
    Proteins: 0,
    Fat: 0,
    Carbohydrates: 11,
    Calorie: 44,
  },
  {
    Name: "Peanut",
    Proteins: 25,
    Fat: 46,
    Carbohydrates: 13,
    Calorie: 561,
  },
  {
    Name: "Arachis in sugar",
    Proteins: 18,
    Fat: 30,
    Carbohydrates: 51,
    Calorie: 535,
  },
  {
    Name: "Fresh basil",
    Proteins: 3,
    Fat: 1,
    Carbohydrates: 4,
    Calorie: 27,
  },
  {
    Name: "Eggplant",
    Proteins: 1,
    Fat: 0,
    Carbohydrates: 6,
    Calorie: 27,
  },
  {
    Name: "Banana",
    Proteins: 3,
    Fat: 3,
    Carbohydrates: 22,
    Calorie: 97,
  },
  {
    Name: "Boiled lamb",
    Proteins: 24,
    Fat: 21,
    Carbohydrates: 0,
    Calorie: 286,
  },
  {
    Name: "Bread",
    Proteins: 8,
    Fat: 3,
    Carbohydrates: 49,
    Calorie: 264,
  },
  {
    Name: "The thigh of the turkey",
    Proteins: 16,
    Fat: 9,
    Carbohydrates: 1,
    Calorie: 143,
  },
  {
    Name: "Bacon",
    Proteins: 15,
    Fat: 45,
    Carbohydrates: 2,
    Calorie: 469,
  },
  {
    Name: "Ordinary pancakes",
    Proteins: 6,
    Fat: 6,
    Carbohydrates: 25,
    Calorie: 178,
  },
  {
    Name: "Borsch is light",
    Proteins: 3,
    Fat: 2,
    Carbohydrates: 9,
    Calorie: 58,
  },
  {
    Name: "Broccoli",
    Proteins: 4,
    Fat: 1,
    Carbohydrates: 4,
    Calorie: 33,
  },
  {
    Name: "Cowberry",
    Proteins: 1,
    Fat: 0,
    Carbohydrates: 9,
    Calorie: 42,
  },
  {
    Name: "Beef broth",
    Proteins: 6,
    Fat: 4,
    Carbohydrates: 0,
    Calorie: 57,
  },
  {
    Name: "Broth of chicken breast",
    Proteins: 7,
    Fat: 1,
    Carbohydrates: 0,
    Calorie: 42,
  },
  {
    Name: "Chicken broth",
    Proteins: 3,
    Fat: 2,
    Carbohydrates: 1,
    Calorie: 33,
  },
  {
    Name: "Boiled beef",
    Proteins: 23,
    Fat: 16,
    Carbohydrates: 0,
    Calorie: 236,
  },
  {
    Name: "Boiled sausage",
    Proteins: 12,
    Fat: 22,
    Carbohydrates: 1,
    Calorie: 253,
  },
  {
    Name: "Boiled chicken breast",
    Proteins: 27,
    Fat: 6,
    Carbohydrates: 1,
    Calorie: 138,
  },
  {
    Name: "Boiled chicken",
    Proteins: 19,
    Fat: 9,
    Carbohydrates: 0,
    Calorie: 150,
  },
  {
    Name: "Boiled carrots",
    Proteins: 1,
    Fat: 0,
    Carbohydrates: 6,
    Calorie: 31,
  },
  {
    Name: "Boiled lentils",
    Proteins: 8,
    Fat: 0,
    Carbohydrates: 20,
    Calorie: 111,
  },
  {
    Name: "Boiled condensed milk",
    Proteins: 7,
    Fat: 9,
    Carbohydrates: 55,
    Calorie: 326,
  },
  {
    Name: "Spaghetti",
    Proteins: 11,
    Fat: 1,
    Carbohydrates: 72,
    Calorie: 347,
  },
  {
    Name: "Ham",
    Proteins: 16,
    Fat: 19,
    Carbohydrates: 2,
    Calorie: 246,
  },
  {
    Name: "White wine",
    Proteins: 0,
    Fat: 0,
    Carbohydrates: 0,
    Calorie: 67,
  },
  {
    Name: "Grape",
    Proteins: 1,
    Fat: 1,
    Carbohydrates: 16,
    Calorie: 69,
  },
  {
    Name: "Dry red wine",
    Proteins: 0,
    Fat: 0,
    Carbohydrates: 1,
    Calorie: 70,
  },
  {
    Name: "Cherry",
    Proteins: 1,
    Fat: 0,
    Carbohydrates: 11,
    Calorie: 54,
  },
  {
    Name: "Oatmeal",
    Proteins: 12,
    Fat: 6,
    Carbohydrates: 56,
    Calorie: 327,
  },
  {
    Name: "Beef",
    Proteins: 20,
    Fat: 13,
    Carbohydrates: 0,
    Calorie: 192,
  },
  {
    Name: "Beef liver",
    Proteins: 17,
    Fat: 3,
    Carbohydrates: 3,
    Calorie: 110,
  },
  {
    Name: "Chicken drumstick",
    Proteins: 20,
    Fat: 9,
    Carbohydrates: 0,
    Calorie: 168,
  },
  {
    Name: "Dutch cheese",
    Proteins: 24,
    Fat: 30,
    Carbohydrates: 0,
    Calorie: 373,
  },
  {
    Name: "Blueberry",
    Proteins: 1,
    Fat: 1,
    Carbohydrates: 9,
    Calorie: 46,
  },
  {
    Name: "Salmon",
    Proteins: 21,
    Fat: 7,
    Carbohydrates: 0,
    Calorie: 143,
  },
  {
    Name: "Peas",
    Proteins: 19,
    Fat: 3,
    Carbohydrates: 42,
    Calorie: 256,
  },
  {
    Name: "Pea mash",
    Proteins: 8,
    Fat: 1,
    Carbohydrates: 23,
    Calorie: 106,
  },
  {
    Name: "Green peas",
    Proteins: 4,
    Fat: 0,
    Carbohydrates: 10,
    Calorie: 59,
  },
  {
    Name: "Mustard",
    Proteins: 8,
    Fat: 11,
    Carbohydrates: 13,
    Calorie: 184,
  },
  {
    Name: "Garnet",
    Proteins: 2,
    Fat: 1,
    Carbohydrates: 14,
    Calorie: 67,
  },
  {
    Name: "Grapefruit",
    Proteins: 1,
    Fat: 0,
    Carbohydrates: 9,
    Calorie: 41,
  },
  {
    Name: "Walnuts",
    Proteins: 15,
    Fat: 65,
    Carbohydrates: 14,
    Calorie: 697,
  },
  {
    Name: "Buckwheat",
    Proteins: 5,
    Fat: 1,
    Carbohydrates: 24,
    Calorie: 131,
  },
  {
    Name: "Buckwheat (in grain)",
    Proteins: 12,
    Fat: 4,
    Carbohydrates: 63,
    Calorie: 329,
  },
  {
    Name: "White mushrooms",
    Proteins: 9,
    Fat: 2,
    Carbohydrates: 3,
    Calorie: 28,
  },
  {
    Name: "White mushrooms (dry)",
    Proteins: 27,
    Fat: 7,
    Carbohydrates: 16,
    Calorie: 239,
  },
  {
    Name: "Milk mushrooms",
    Proteins: 2,
    Fat: 1,
    Carbohydrates: 1,
    Calorie: 16,
  },
  {
    Name: "Chanterelles",
    Proteins: 2,
    Fat: 1,
    Carbohydrates: 1,
    Calorie: 20,
  },
  {
    Name: "Champignon mushrooms",
    Proteins: 4,
    Fat: 1,
    Carbohydrates: 0,
    Calorie: 22,
  },
  {
    Name: "Pear",
    Proteins: 1,
    Fat: 0,
    Carbohydrates: 12,
    Calorie: 51,
  },
  {
    Name: "Pear (dried fruits)",
    Proteins: 2,
    Fat: 0,
    Carbohydrates: 62,
    Calorie: 246,
  },
  {
    Name: "Jam Mandarin",
    Proteins: 0,
    Fat: 0,
    Carbohydrates: 72,
    Calorie: 276,
  },
  {
    Name: "Yeast",
    Proteins: 29,
    Fat: 3,
    Carbohydrates: 23,
    Calorie: 263,
  },
  {
    Name: "Dry yeast",
    Proteins: 49,
    Fat: 6,
    Carbohydrates: 40,
    Calorie: 410,
  },
  {
    Name: "Melon",
    Proteins: 1,
    Fat: 0,
    Carbohydrates: 8,
    Calorie: 35,
  },
  {
    Name: "Blackberry",
    Proteins: 2,
    Fat: 0,
    Carbohydrates: 5,
    Calorie: 31,
  },
  {
    Name: "Fried egg",
    Proteins: 14,
    Fat: 14,
    Carbohydrates: 1,
    Calorie: 183,
  },
  {
    Name: "Gelatin",
    Proteins: 86,
    Fat: 0,
    Carbohydrates: 1,
    Calorie: 343,
  },
  {
    Name: "Green beans",
    Proteins: 3,
    Fat: 0,
    Carbohydrates: 4,
    Calorie: 30,
  },
  {
    Name: "Green onions",
    Proteins: 1,
    Fat: 0,
    Carbohydrates: 4,
    Calorie: 19,
  },
  {
    Name: "Parsley",
    Proteins: 4,
    Fat: 0,
    Carbohydrates: 8,
    Calorie: 50,
  },
  {
    Name: "Green peas 'Bonduel'",
    Proteins: 5,
    Fat: 0,
    Carbohydrates: 8,
    Calorie: 60,
  },
  {
    Name: "Green peas 'Frau Marta'",
    Proteins: 3,
    Fat: 0,
    Carbohydrates: 7,
    Calorie: 40,
  },
  {
    Name: "Strawberries",
    Proteins: 1,
    Fat: 0,
    Carbohydrates: 9,
    Calorie: 38,
  },
  {
    Name: "Marshmallow",
    Proteins: 1,
    Fat: 0,
    Carbohydrates: 80,
    Calorie: 304,
  },
  {
    Name: "Raisin",
    Proteins: 2,
    Fat: 0,
    Carbohydrates: 68,
    Calorie: 280,
  },
  {
    Name: "Fresh ginger",
    Proteins: 2,
    Fat: 1,
    Carbohydrates: 16,
    Calorie: 72,
  },
  {
    Name: "Turkey (breast)",
    Proteins: 19,
    Fat: 2,
    Carbohydrates: 0,
    Calorie: 94,
  },
  {
    Name: "Turkey (fillet)",
    Proteins: 20,
    Fat: 12,
    Carbohydrates: 0,
    Calorie: 188,
  },
  {
    Name: "Figs (dried fruits)",
    Proteins: 3,
    Fat: 1,
    Carbohydrates: 57,
    Calorie: 239,
  },
  {
    Name: "Yogurt",
    Proteins: 4,
    Fat: 3,
    Carbohydrates: 11,
    Calorie: 97,
  },
  {
    Name: "Zucchini fried",
    Proteins: 1,
    Fat: 6,
    Carbohydrates: 7,
    Calorie: 91,
  },
  {
    Name: "Zucchini",
    Proteins: 2,
    Fat: 0,
    Carbohydrates: 3,
    Calorie: 16,
  },
  {
    Name: "Squash caviar",
    Proteins: 1,
    Fat: 6,
    Carbohydrates: 7,
    Calorie: 90,
  },
  {
    Name: "Zucchini",
    Proteins: 1,
    Fat: 1,
    Carbohydrates: 5,
    Calorie: 28,
  },
  {
    Name: "Cocoa",
    Proteins: 14,
    Fat: 9,
    Carbohydrates: 26,
    Calorie: 234,
  },
  {
    Name: "Cocoa powder",
    Proteins: 23,
    Fat: 15,
    Carbohydrates: 29,
    Calorie: 326,
  },
  {
    Name: "Squid",
    Proteins: 18,
    Fat: 2,
    Carbohydrates: 1,
    Calorie: 97,
  },
  {
    Name: "Calmar boiled",
    Proteins: 18,
    Fat: 3,
    Carbohydrates: 1,
    Calorie: 103,
  },
  {
    Name: "Capers",
    Proteins: 2,
    Fat: 1,
    Carbohydrates: 4,
    Calorie: 21,
  },
  {
    Name: "White cabbage",
    Proteins: 2,
    Fat: 0,
    Carbohydrates: 5,
    Calorie: 28,
  },
  {
    Name: "Broccoli cabbage is frozen",
    Proteins: 2,
    Fat: 0,
    Carbohydrates: 4,
    Calorie: 21,
  },
  {
    Name: "Brussels cabbage",
    Proteins: 4,
    Fat: 0,
    Carbohydrates: 4,
    Calorie: 47,
  },
  {
    Name: "Cabbage is fried",
    Proteins: 3,
    Fat: 6,
    Carbohydrates: 8,
    Calorie: 88,
  },
  {
    Name: "Sauerkraut",
    Proteins: 2,
    Fat: 0,
    Carbohydrates: 3,
    Calorie: 23,
  },
  {
    Name: "Cabbage of Kohlrabi",
    Proteins: 3,
    Fat: 0,
    Carbohydrates: 9,
    Calorie: 42,
  },
  {
    Name: "Red cabbage",
    Proteins: 2,
    Fat: 0,
    Carbohydrates: 6,
    Calorie: 29,
  },
  {
    Name: "Cabbage sea",
    Proteins: 1,
    Fat: 5,
    Carbohydrates: 0,
    Calorie: 58,
  },
  {
    Name: "Cabbage",
    Proteins: 2,
    Fat: 0,
    Carbohydrates: 3,
    Calorie: 15,
  },
  {
    Name: "Cauliflower",
    Proteins: 3,
    Fat: 0,
    Carbohydrates: 5,
    Calorie: 34,
  },
  {
    Name: "Potato",
    Proteins: 2,
    Fat: 1,
    Carbohydrates: 20,
    Calorie: 84,
  },
  {
    Name: "Young potato",
    Proteins: 2,
    Fat: 0,
    Carbohydrates: 16,
    Calorie: 61,
  },
  {
    Name: "Potato flakes",
    Proteins: 8,
    Fat: 1,
    Carbohydrates: 83,
    Calorie: 366,
  },
  {
    Name: "Boiled potatoes",
    Proteins: 2,
    Fat: 1,
    Carbohydrates: 16,
    Calorie: 83,
  },
  {
    Name: "Potatoes baked",
    Proteins: 3,
    Fat: 3,
    Carbohydrates: 22,
    Calorie: 113,
  },
  {
    Name: "French fries",
    Proteins: 4,
    Fat: 17,
    Carbohydrates: 40,
    Calorie: 323,
  },
  {
    Name: "Rice porridge",
    Proteins: 2,
    Fat: 3,
    Carbohydrates: 26,
    Calorie: 130,
  },
  {
    Name: "Kvass bread",
    Proteins: 0,
    Fat: 0,
    Carbohydrates: 5,
    Calorie: 24,
  },
  {
    Name: "Pine nuts",
    Proteins: 15,
    Fat: 63,
    Carbohydrates: 17,
    Calorie: 652,
  },
  {
    Name: "Ketchup",
    Proteins: 5,
    Fat: 1,
    Carbohydrates: 16,
    Calorie: 90,
  },
  {
    Name: "Kefir 1%",
    Proteins: 3,
    Fat: 1,
    Carbohydrates: 5,
    Calorie: 45,
  },
  {
    Name: "Kefir 2.5%",
    Proteins: 3,
    Fat: 3,
    Carbohydrates: 4,
    Calorie: 52,
  },
  {
    Name: "Kefir 3.2%",
    Proteins: 3,
    Fat: 3,
    Carbohydrates: 4,
    Calorie: 58,
  },
  {
    Name: "Cashew nuts",
    Proteins: 21,
    Fat: 48,
    Carbohydrates: 20,
    Calorie: 607,
  },
  {
    Name: "Kiwi",
    Proteins: 1,
    Fat: 1,
    Carbohydrates: 10,
    Calorie: 51,
  },
  {
    Name: "Strawberry",
    Proteins: 1,
    Fat: 0,
    Carbohydrates: 7,
    Calorie: 32,
  },
  {
    Name: "Cranberry",
    Proteins: 0,
    Fat: 0,
    Carbohydrates: 9,
    Calorie: 43,
  },
  {
    Name: "Cranberry is dried",
    Proteins: 0,
    Fat: 1,
    Carbohydrates: 70,
    Calorie: 305,
  },
  {
    Name: "Goat cheese",
    Proteins: 19,
    Fat: 23,
    Carbohydrates: 2,
    Calorie: 296,
  },
  {
    Name: "Ginger root",
    Proteins: 2,
    Fat: 1,
    Carbohydrates: 18,
    Calorie: 90,
  },
  {
    Name: "Celery root",
    Proteins: 1,
    Fat: 0,
    Carbohydrates: 6,
    Calorie: 31,
  },
  {
    Name: "Brown sugar",
    Proteins: 0,
    Fat: 0,
    Carbohydrates: 92,
    Calorie: 393,
  },
  {
    Name: "Pickled cornishons",
    Proteins: 1,
    Fat: 0,
    Carbohydrates: 4,
    Calorie: 36,
  },
  {
    Name: "Cutlets",
    Proteins: 26,
    Fat: 32,
    Carbohydrates: 6,
    Calorie: 415,
  },
  {
    Name: "Ground coffee Arabica",
    Proteins: 12,
    Fat: 14,
    Carbohydrates: 3,
    Calorie: 193,
  },
  {
    Name: "Soluble coffee (dry)",
    Proteins: 15,
    Fat: 4,
    Carbohydrates: 7,
    Calorie: 116,
  },
  {
    Name: "Espresso coffee (strong)",
    Proteins: 1,
    Fat: 2,
    Carbohydrates: 0,
    Calorie: 19,
  },
  {
    Name: "Crab sticks",
    Proteins: 8,
    Fat: 2,
    Carbohydrates: 10,
    Calorie: 85,
  },
  {
    Name: "Krakow sausage",
    Proteins: 17,
    Fat: 39,
    Carbohydrates: 0,
    Calorie: 420,
  },
  {
    Name: "Red beans are canned",
    Proteins: 7,
    Fat: 0,
    Carbohydrates: 17,
    Calorie: 99,
  },
  {
    Name: "Potato starch",
    Proteins: 0,
    Fat: 0,
    Carbohydrates: 82,
    Calorie: 335,
  },
  {
    Name: "Corn starch",
    Proteins: 1,
    Fat: 0,
    Carbohydrates: 87,
    Calorie: 348,
  },
  {
    Name: "Shrimp (boiled)",
    Proteins: 18,
    Fat: 2,
    Carbohydrates: 0,
    Calorie: 90,
  },
  {
    Name: "Buckwheat",
    Proteins: 12,
    Fat: 3,
    Carbohydrates: 65,
    Calorie: 326,
  },
  {
    Name: "Corn grits",
    Proteins: 8,
    Fat: 1,
    Carbohydrates: 75,
    Calorie: 337,
  },
  {
    Name: "Semolina groats",
    Proteins: 11,
    Fat: 1,
    Carbohydrates: 70,
    Calorie: 330,
  },
  {
    Name: "Pearl groats",
    Proteins: 10,
    Fat: 1,
    Carbohydrates: 65,
    Calorie: 328,
  },
  {
    Name: "Wheat groats",
    Proteins: 12,
    Fat: 2,
    Carbohydrates: 63,
    Calorie: 322,
  },
  {
    Name: "Rice groats",
    Proteins: 7,
    Fat: 11,
    Carbohydrates: 63,
    Calorie: 330,
  },
  {
    Name: "Barley groats",
    Proteins: 10,
    Fat: 1,
    Carbohydrates: 59,
    Calorie: 318,
  },
  {
    Name: "Gooseberry",
    Proteins: 1,
    Fat: 0,
    Carbohydrates: 10,
    Calorie: 41,
  },
  {
    Name: "Corn canned",
    Proteins: 3,
    Fat: 2,
    Carbohydrates: 17,
    Calorie: 87,
  },
  {
    Name: "Cornflakes",
    Proteins: 6,
    Fat: 3,
    Carbohydrates: 73,
    Calorie: 353,
  },
  {
    Name: "Sesame",
    Proteins: 20,
    Fat: 50,
    Carbohydrates: 11,
    Calorie: 562,
  },
  {
    Name: "Dried apricots",
    Proteins: 5,
    Fat: 0,
    Carbohydrates: 54,
    Calorie: 232,
  },
  {
    Name: "Chicken liver",
    Proteins: 19,
    Fat: 7,
    Carbohydrates: 1,
    Calorie: 140,
  },
  {
    Name: "Chicken breasts",
    Proteins: 23,
    Fat: 6,
    Carbohydrates: 3,
    Calorie: 144,
  },
  {
    Name: "Chicken legs",
    Proteins: 18,
    Fat: 11,
    Carbohydrates: 0,
    Calorie: 170,
  },
  {
    Name: "Chicken",
    Proteins: 21,
    Fat: 11,
    Carbohydrates: 1,
    Calorie: 186,
  },
  {
    Name: "Cuscu (cereal)",
    Proteins: 13,
    Fat: 1,
    Carbohydrates: 77,
    Calorie: 373,
  },
  {
    Name: "Lavash Georgian",
    Proteins: 8,
    Fat: 2,
    Carbohydrates: 53,
    Calorie: 269,
  },
  {
    Name: "Lime",
    Proteins: 1,
    Fat: 0,
    Carbohydrates: 4,
    Calorie: 20,
  },
  {
    Name: "Buckwheat noodles",
    Proteins: 15,
    Fat: 1,
    Carbohydrates: 71,
    Calorie: 348,
  },
  {
    Name: "Rice noodles",
    Proteins: 5,
    Fat: 1,
    Carbohydrates: 81,
    Calorie: 350,
  },
  {
    Name: "Egg noodles",
    Proteins: 10,
    Fat: 2,
    Carbohydrates: 64,
    Calorie: 330,
  },
  {
    Name: "Lemon",
    Proteins: 1,
    Fat: 0,
    Carbohydrates: 4,
    Calorie: 27,
  },
  {
    Name: "Lemon juice",
    Proteins: 1,
    Fat: 0,
    Carbohydrates: 4,
    Calorie: 20,
  },
  {
    Name: "Salmon",
    Proteins: 21,
    Fat: 10,
    Carbohydrates: 1,
    Calorie: 172,
  },
  {
    Name: "Onion",
    Proteins: 1,
    Fat: 0,
    Carbohydrates: 9,
    Calorie: 40,
  },
  {
    Name: "Onion green feather",
    Proteins: 1,
    Fat: 0,
    Carbohydrates: 5,
    Calorie: 16,
  },
  {
    Name: "Red onion",
    Proteins: 1,
    Fat: 0,
    Carbohydrates: 9,
    Calorie: 42,
  },
  {
    Name: "Linseed oil",
    Proteins: 1,
    Fat: 92,
    Carbohydrates: 4,
    Calorie: 849,
  },
  {
    Name: "Mayonnaise",
    Proteins: 2,
    Fat: 57,
    Carbohydrates: 4,
    Calorie: 550,
  },
  {
    Name: "Mayonnaise 15%",
    Proteins: 0,
    Fat: 15,
    Carbohydrates: 5,
    Calorie: 156,
  },
  {
    Name: "Mayonnaise Provensal 67%",
    Proteins: 3,
    Fat: 369,
    Carbohydrates: 25,
    Calorie: 619,
  },
  {
    Name: "Poppy",
    Proteins: 17,
    Fat: 46,
    Carbohydrates: 8,
    Calorie: 519,
  },
  {
    Name: "Pasta",
    Proteins: 10,
    Fat: 0,
    Carbohydrates: 72,
    Calorie: 344,
  },
  {
    Name: "Boiled pasta",
    Proteins: 4,
    Fat: 1,
    Carbohydrates: 23,
    Calorie: 119,
  },
  {
    Name: "Raspberry",
    Proteins: 4,
    Fat: 0,
    Carbohydrates: 9,
    Calorie: 41,
  },
  {
    Name: "Mango",
    Proteins: 1,
    Fat: 0,
    Carbohydrates: 13,
    Calorie: 62,
  },
  {
    Name: "Mango Tsukata",
    Proteins: 0,
    Fat: 0,
    Carbohydrates: 60,
    Calorie: 278,
  },
  {
    Name: "Mandarin",
    Proteins: 1,
    Fat: 1,
    Carbohydrates: 9,
    Calorie: 40,
  },
  {
    Name: "Marmelad",
    Proteins: 1,
    Fat: 0,
    Carbohydrates: 75,
    Calorie: 302,
  },
  {
    Name: "Maslins",
    Proteins: 1,
    Fat: 14,
    Carbohydrates: 10,
    Calorie: 167,
  },
  {
    Name: "Maslins without a bone",
    Proteins: 1,
    Fat: 13,
    Carbohydrates: 2,
    Calorie: 133,
  },
  {
    Name: "Corn oil",
    Proteins: 1,
    Fat: 101,
    Carbohydrates: 0,
    Calorie: 916,
  },
  {
    Name: "Flaxseed oil",
    Proteins: 0,
    Fat: 96,
    Carbohydrates: 0,
    Calorie: 895,
  },
  {
    Name: "Olive oil",
    Proteins: 1,
    Fat: 91,
    Carbohydrates: 3,
    Calorie: 851,
  },
  {
    Name: "Sunflower oil",
    Proteins: 0,
    Fat: 96,
    Carbohydrates: 0,
    Calorie: 864,
  },
  {
    Name: "Vegetable oil",
    Proteins: 2,
    Fat: 97,
    Carbohydrates: 0,
    Calorie: 897,
  },
  {
    Name: "Butter",
    Proteins: 1,
    Fat: 74,
    Carbohydrates: 1,
    Calorie: 674,
  },
  {
    Name: "The oil is ghee",
    Proteins: 0,
    Fat: 86,
    Carbohydrates: 0,
    Calorie: 890,
  },
  {
    Name: "Honey",
    Proteins: 1,
    Fat: 0,
    Carbohydrates: 80,
    Calorie: 315,
  },
  {
    Name: "Almond",
    Proteins: 18,
    Fat: 51,
    Carbohydrates: 16,
    Calorie: 601,
  },
  {
    Name: "Milk",
    Proteins: 7,
    Fat: 3,
    Carbohydrates: 7,
    Calorie: 66,
  },
  {
    Name: "Milk 0.5%",
    Proteins: 2,
    Fat: 1,
    Carbohydrates: 3,
    Calorie: 35,
  },
  {
    Name: "Milk 1.5%",
    Proteins: 3,
    Fat: 2,
    Carbohydrates: 5,
    Calorie: 44,
  },
  {
    Name: "Milk 2.5%",
    Proteins: 3,
    Fat: 3,
    Carbohydrates: 7,
    Calorie: 64,
  },
  {
    Name: "Milk 3.2%",
    Proteins: 3,
    Fat: 3,
    Carbohydrates: 8,
    Calorie: 67,
  },
  {
    Name: "The milk is condensed",
    Proteins: 7,
    Fat: 9,
    Carbohydrates: 56,
    Calorie: 317,
  },
  {
    Name: "Dry milk",
    Proteins: 31,
    Fat: 22,
    Carbohydrates: 36,
    Calorie: 446,
  },
  {
    Name: "Boiled carrots",
    Proteins: 1,
    Fat: 0,
    Carbohydrates: 7,
    Calorie: 32,
  },
  {
    Name: "Big carrots",
    Proteins: 1,
    Fat: 0,
    Carbohydrates: 7,
    Calorie: 31,
  },
  {
    Name: "Fresh carrots",
    Proteins: 1,
    Fat: 0,
    Carbohydrates: 8,
    Calorie: 35,
  },
  {
    Name: "Corn flour",
    Proteins: 9,
    Fat: 3,
    Carbohydrates: 65,
    Calorie: 333,
  },
  {
    Name: "Wheat flour in/s",
    Proteins: 10,
    Fat: 1,
    Carbohydrates: 71,
    Calorie: 332,
  },
  {
    Name: "Rye flour",
    Proteins: 8,
    Fat: 2,
    Carbohydrates: 65,
    Calorie: 307,
  },
  {
    Name: "Mustli with fruits",
    Proteins: 8,
    Fat: 2,
    Carbohydrates: 68,
    Calorie: 314,
  },
  {
    Name: "Pork meat",
    Proteins: 26,
    Fat: 29,
    Carbohydrates: 7,
    Calorie: 293,
  },
  {
    Name: "Lean pork meat",
    Proteins: 18,
    Fat: 8,
    Carbohydrates: 0,
    Calorie: 151,
  },
  {
    Name: "Nectarine",
    Proteins: 1,
    Fat: 0,
    Carbohydrates: 11,
    Calorie: 47,
  },
  {
    Name: "Sea ​​buckthorn",
    Proteins: 1,
    Fat: 2,
    Carbohydrates: 6,
    Calorie: 47,
  },
  {
    Name: "Cucumbers",
    Proteins: 1,
    Fat: 0,
    Carbohydrates: 4,
    Calorie: 19,
  },
  {
    Name: "Ground cucumbers",
    Proteins: 1,
    Fat: 0,
    Carbohydrates: 3,
    Calorie: 14,
  },
  {
    Name: "Pickled cucumbers",
    Proteins: 2,
    Fat: 0,
    Carbohydrates: 2,
    Calorie: 16,
  },
  {
    Name: "Pickles",
    Proteins: 1,
    Fat: 0,
    Carbohydrates: 2,
    Calorie: 14,
  },
  {
    Name: "Olives",
    Proteins: 1,
    Fat: 17,
    Carbohydrates: 5,
    Calorie: 178,
  },
  {
    Name: "Green olives without a bone",
    Proteins: 1,
    Fat: 17,
    Carbohydrates: 0,
    Calorie: 157,
  },
  {
    Name: "Omelette",
    Proteins: 10,
    Fat: 14,
    Carbohydrates: 3,
    Calorie: 175,
  },
  {
    Name: "Paprika",
    Proteins: 3,
    Fat: 2,
    Carbohydrates: 7,
    Calorie: 112,
  },
  {
    Name: "Squash",
    Proteins: 1,
    Fat: 0,
    Carbohydrates: 4,
    Calorie: 19,
  },
  {
    Name: "Quail egg",
    Proteins: 13,
    Fat: 13,
    Carbohydrates: 0,
    Calorie: 167,
  },
  {
    Name: "Sweet pepper",
    Proteins: 1,
    Fat: 0,
    Carbohydrates: 5,
    Calorie: 26,
  },
  {
    Name: "Chilli",
    Proteins: 2,
    Fat: 0,
    Carbohydrates: 9,
    Calorie: 40,
  },
  {
    Name: "Persian",
    Proteins: 1,
    Fat: 1,
    Carbohydrates: 12,
    Calorie: 51,
  },
  {
    Name: "Persians (dried fruits)",
    Proteins: 2,
    Fat: 0,
    Carbohydrates: 42,
    Calorie: 168,
  },
  {
    Name: "Parsley root",
    Proteins: 2,
    Fat: 0,
    Carbohydrates: 11,
    Calorie: 48,
  },
  {
    Name: "Parsley is fresh",
    Proteins: 3,
    Fat: 1,
    Carbohydrates: 7,
    Calorie: 38,
  },
  {
    Name: "Chicken liver",
    Proteins: 27,
    Fat: 7,
    Carbohydrates: 1,
    Calorie: 144,
  },
  {
    Name: "The beer is light",
    Proteins: 0,
    Fat: 0,
    Carbohydrates: 4,
    Calorie: 50,
  },
  {
    Name: "Flated cheese",
    Proteins: 15,
    Fat: 20,
    Carbohydrates: 2,
    Calorie: 280,
  },
  {
    Name: "Caught tomatoes",
    Proteins: 1,
    Fat: 0,
    Carbohydrates: 5,
    Calorie: 23,
  },
  {
    Name: "Fresh tomatoes",
    Proteins: 4,
    Fat: 1,
    Carbohydrates: 3,
    Calorie: 33,
  },
  {
    Name: "Millet",
    Proteins: 11,
    Fat: 3,
    Carbohydrates: 68,
    Calorie: 337,
  },
  {
    Name: "Roar of a cherry",
    Proteins: 1,
    Fat: 0,
    Carbohydrates: 4,
    Calorie: 16,
  },
  {
    Name: "Radish",
    Proteins: 1,
    Fat: 0,
    Carbohydrates: 4,
    Calorie: 20,
  },
  {
    Name: "Radish",
    Proteins: 2,
    Fat: 0,
    Carbohydrates: 7,
    Calorie: 35,
  },
  {
    Name: "Green radish",
    Proteins: 2,
    Fat: 0,
    Carbohydrates: 7,
    Calorie: 35,
  },
  {
    Name: "Turnip",
    Proteins: 1,
    Fat: 0,
    Carbohydrates: 5,
    Calorie: 29,
  },
  {
    Name: "Rice",
    Proteins: 7,
    Fat: 1,
    Carbohydrates: 75,
    Calorie: 331,
  },
  {
    Name: "Boiled horns",
    Proteins: 3,
    Fat: 0,
    Carbohydrates: 24,
    Calorie: 115,
  },
  {
    Name: "Rugula",
    Proteins: 2,
    Fat: 1,
    Carbohydrates: 2,
    Calorie: 24,
  },
  {
    Name: "Fish mackerel",
    Proteins: 16,
    Fat: 13,
    Carbohydrates: 1,
    Calorie: 187,
  },
  {
    Name: "Cod fish",
    Proteins: 17,
    Fat: 1,
    Carbohydrates: 0,
    Calorie: 80,
  },
  {
    Name: "Salad leaf",
    Proteins: 1,
    Fat: 0,
    Carbohydrates: 2,
    Calorie: 16,
  },
  {
    Name: "Sugar sand",
    Proteins: 0,
    Fat: 0,
    Carbohydrates: 109,
    Calorie: 396,
  },
  {
    Name: "Fresh cabbage",
    Proteins: 2,
    Fat: 0,
    Carbohydrates: 5,
    Calorie: 25,
  },
  {
    Name: "Fresh dill",
    Proteins: 3,
    Fat: 1,
    Carbohydrates: 6,
    Calorie: 38,
  },
  {
    Name: "Beet",
    Proteins: 2,
    Fat: 1,
    Carbohydrates: 12,
    Calorie: 61,
  },
  {
    Name: "Boiled beets",
    Proteins: 2,
    Fat: 0,
    Carbohydrates: 10,
    Calorie: 50,
  },
  {
    Name: "Celery",
    Proteins: 1,
    Fat: 0,
    Carbohydrates: 3,
    Calorie: 13,
  },
  {
    Name: "Celery stem",
    Proteins: 1,
    Fat: 0,
    Carbohydrates: 2,
    Calorie: 11,
  },
  {
    Name: "The herring of the Atlantic fat",
    Proteins: 15,
    Fat: 15,
    Carbohydrates: 0,
    Calorie: 204,
  },
  {
    Name: "Pumpkin seeds unpeeled with salt",
    Proteins: 29,
    Fat: 47,
    Carbohydrates: 13,
    Calorie: 596,
  },
  {
    Name: "Sunflower seeds",
    Proteins: 26,
    Fat: 50,
    Carbohydrates: 9,
    Calorie: 583,
  },
  {
    Name: "Sweet corn in cobs",
    Proteins: 4,
    Fat: 3,
    Carbohydrates: 21,
    Calorie: 124,
  },
  {
    Name: "Cream 10%",
    Proteins: 3,
    Fat: 10,
    Carbohydrates: 4,
    Calorie: 118,
  },
  {
    Name: "Cream 20%",
    Proteins: 3,
    Fat: 20,
    Carbohydrates: 4,
    Calorie: 206,
  },
  {
    Name: "Cream 22%",
    Proteins: 3,
    Fat: 22,
    Carbohydrates: 4,
    Calorie: 224,
  },
  {
    Name: "Cream 33%",
    Proteins: 2,
    Fat: 33,
    Carbohydrates: 4,
    Calorie: 322,
  },
  {
    Name: "A mixture of nuts and dried fruits exotic",
    Proteins: 8,
    Fat: 26,
    Carbohydrates: 52,
    Calorie: 466,
  },
  {
    Name: "Sour cream 10 %",
    Proteins: 3,
    Fat: 10,
    Carbohydrates: 4,
    Calorie: 117,
  },
  {
    Name: "Sour cream 15%",
    Proteins: 3,
    Fat: 15,
    Carbohydrates: 4,
    Calorie: 159,
  },
  {
    Name: "Sour cream 20%",
    Proteins: 3,
    Fat: 19,
    Carbohydrates: 6,
    Calorie: 204,
  },
  {
    Name: "Sour cream 30 %",
    Proteins: 2,
    Fat: 30,
    Carbohydrates: 3,
    Calorie: 291,
  },
  {
    Name: "Red currants",
    Proteins: 1,
    Fat: 0,
    Carbohydrates: 8,
    Calorie: 40,
  },
  {
    Name: "Currant is black",
    Proteins: 1,
    Fat: 0,
    Carbohydrates: 9,
    Calorie: 41,
  },
  {
    Name: "Soy sauce",
    Proteins: 5,
    Fat: 0,
    Carbohydrates: 22,
    Calorie: 36,
  },
  {
    Name: "Orange juice",
    Proteins: 1,
    Fat: 0,
    Carbohydrates: 11,
    Calorie: 47,
  },
  {
    Name: "Grapefruit juice",
    Proteins: 0,
    Fat: 0,
    Carbohydrates: 10,
    Calorie: 44,
  },
  {
    Name: "Lyme juice",
    Proteins: 1,
    Fat: 0,
    Carbohydrates: 6,
    Calorie: 22,
  },
  {
    Name: "Lemon juice",
    Proteins: 1,
    Fat: 0,
    Carbohydrates: 5,
    Calorie: 29,
  },
  {
    Name: "Mandarin juice",
    Proteins: 1,
    Fat: 0,
    Carbohydrates: 10,
    Calorie: 43,
  },
  {
    Name: "The juice is beetroot",
    Proteins: 1,
    Fat: 0,
    Carbohydrates: 14,
    Calorie: 61,
  },
  {
    Name: "The juice is tomato",
    Proteins: 0,
    Fat: 0,
    Carbohydrates: 5,
    Calorie: 21,
  },
  {
    Name: "Apple juice",
    Proteins: 0,
    Fat: 0,
    Carbohydrates: 10,
    Calorie: 44,
  },
  {
    Name: "Pickle",
    Proteins: 1,
    Fat: 0,
    Carbohydrates: 3,
    Calorie: 14,
  },
  {
    Name: "Soy sauce",
    Proteins: 4,
    Fat: 0,
    Carbohydrates: 10,
    Calorie: 53,
  },
  {
    Name: "Soy",
    Proteins: 34,
    Fat: 12,
    Carbohydrates: 27,
    Calorie: 359,
  },
  {
    Name: "Spaghetti boiled",
    Proteins: 7,
    Fat: 1,
    Carbohydrates: 46,
    Calorie: 223,
  },
  {
    Name: "Spaghetti (dry product)",
    Proteins: 10,
    Fat: 1,
    Carbohydrates: 72,
    Calorie: 344,
  },
  {
    Name: "Breadcrumbs",
    Proteins: 12,
    Fat: 2,
    Carbohydrates: 74,
    Calorie: 362,
  },
  {
    Name: "Serum",
    Proteins: 1,
    Fat: 0,
    Carbohydrates: 4,
    Calorie: 22,
  },
  {
    Name: "Cheese 45%",
    Proteins: 26,
    Fat: 26,
    Carbohydrates: 0,
    Calorie: 336,
  },
  {
    Name: "Adygea cheese",
    Proteins: 18,
    Fat: 16,
    Carbohydrates: 0,
    Calorie: 224,
  },
  {
    Name: "The cheese of Gauda",
    Proteins: 24,
    Fat: 27,
    Carbohydrates: 2,
    Calorie: 350,
  },
  {
    Name: "Cheese 'Russian'",
    Proteins: 23,
    Fat: 29,
    Carbohydrates: 0,
    Calorie: 361,
  },
  {
    Name: "Hard cheese",
    Proteins: 25,
    Fat: 27,
    Carbohydrates: 2,
    Calorie: 358,
  },
  {
    Name: "Cottage cheese 0%",
    Proteins: 16,
    Fat: 0,
    Carbohydrates: 2,
    Calorie: 75,
  },
  {
    Name: "Cottage cheese 1%",
    Proteins: 17,
    Fat: 1,
    Carbohydrates: 2,
    Calorie: 82,
  },
  {
    Name: "Cottage cheese 10%",
    Proteins: 15,
    Fat: 9,
    Carbohydrates: 2,
    Calorie: 150,
  },
  {
    Name: "Cottage cheese 5 %",
    Proteins: 17,
    Fat: 5,
    Carbohydrates: 2,
    Calorie: 122,
  },
  {
    Name: "Cottage cheese 9%",
    Proteins: 16,
    Fat: 8,
    Carbohydrates: 3,
    Calorie: 153,
  },
  {
    Name: "Cottage cheese",
    Proteins: 7,
    Fat: 21,
    Carbohydrates: 33,
    Calorie: 349,
  },
  {
    Name: "The dough is yeast",
    Proteins: 7,
    Fat: 4,
    Carbohydrates: 43,
    Calorie: 238,
  },
  {
    Name: "Tomato",
    Proteins: 1,
    Fat: 0,
    Carbohydrates: 5,
    Calorie: 27,
  },
  {
    Name: "Tomato paste tomato",
    Proteins: 1,
    Fat: 0,
    Carbohydrates: 15,
    Calorie: 77,
  },
  {
    Name: "Tomato juice",
    Proteins: 1,
    Fat: 0,
    Carbohydrates: 4,
    Calorie: 25,
  },
  {
    Name: "Tomati cherry",
    Proteins: 1,
    Fat: 0,
    Carbohydrates: 3,
    Calorie: 17,
  },
  {
    Name: "Cod fillet",
    Proteins: 17,
    Fat: 1,
    Carbohydrates: 0,
    Calorie: 78,
  },
  {
    Name: "Pumpkin",
    Proteins: 1,
    Fat: 0,
    Carbohydrates: 5,
    Calorie: 22,
  },
  {
    Name: "Dill",
    Proteins: 3,
    Fat: 1,
    Carbohydrates: 6,
    Calorie: 38,
  },
  {
    Name: "Tining vinegar 6-7%",
    Proteins: 0,
    Fat: 0,
    Carbohydrates: 6,
    Calorie: 13,
  },
  {
    Name: "Ground beef",
    Proteins: 18,
    Fat: 16,
    Carbohydrates: 0,
    Calorie: 214,
  },
  {
    Name: "The minced meat is chicken",
    Proteins: 19,
    Fat: 10,
    Carbohydrates: 0,
    Calorie: 166,
  },
  {
    Name: "Beans",
    Proteins: 18,
    Fat: 1,
    Carbohydrates: 44,
    Calorie: 263,
  },
  {
    Name: "Fennel",
    Proteins: 1,
    Fat: 0,
    Carbohydrates: 7,
    Calorie: 31,
  },
  {
    Name: "Chicken fillet",
    Proteins: 23,
    Fat: 2,
    Carbohydrates: 0,
    Calorie: 114,
  },
  {
    Name: "Fillet chicken breast",
    Proteins: 22,
    Fat: 2,
    Carbohydrates: 0,
    Calorie: 109,
  },
  {
    Name: "Dates (dried fruits)",
    Proteins: 2,
    Fat: 0,
    Carbohydrates: 72,
    Calorie: 280,
  },
  {
    Name: "Fructose",
    Proteins: 0,
    Fat: 0,
    Carbohydrates: 100,
    Calorie: 390,
  },
  {
    Name: "Hazelnut",
    Proteins: 15,
    Fat: 62,
    Carbohydrates: 11,
    Calorie: 665,
  },
  {
    Name: "White bread",
    Proteins: 8,
    Fat: 3,
    Carbohydrates: 54,
    Calorie: 254,
  },
  {
    Name: "Bread 'Borodinsky'",
    Proteins: 7,
    Fat: 1,
    Carbohydrates: 42,
    Calorie: 210,
  },
  {
    Name: "Wheat bread",
    Proteins: 8,
    Fat: 3,
    Carbohydrates: 50,
    Calorie: 263,
  },
  {
    Name: "Rye bread",
    Proteins: 7,
    Fat: 1,
    Carbohydrates: 36,
    Calorie: 187,
  },
  {
    Name: "Wheat bread",
    Proteins: 12,
    Fat: 2,
    Carbohydrates: 60,
    Calorie: 305,
  },
  {
    Name: "Cornflakes",
    Proteins: 7,
    Fat: 1,
    Carbohydrates: 84,
    Calorie: 373,
  },
  {
    Name: "Oatmeal flakes",
    Proteins: 12,
    Fat: 6,
    Carbohydrates: 52,
    Calorie: 308,
  },
  {
    Name: "Horseradish",
    Proteins: 3,
    Fat: 5,
    Carbohydrates: 14,
    Calorie: 113,
  },
  {
    Name: "Persimmon",
    Proteins: 1,
    Fat: 0,
    Carbohydrates: 15,
    Calorie: 65,
  },
  {
    Name: "Orange zest",
    Proteins: 1,
    Fat: 0,
    Carbohydrates: 6,
    Calorie: 36,
  },
  {
    Name: "Lemon zest",
    Proteins: 1,
    Fat: 0,
    Carbohydrates: 4,
    Calorie: 28,
  },
  {
    Name: "Candied fruit",
    Proteins: 3,
    Fat: 0,
    Carbohydrates: 56,
    Calorie: 224,
  },
  {
    Name: "Tsukini",
    Proteins: 2,
    Fat: 0,
    Carbohydrates: 3,
    Calorie: 18,
  },
  {
    Name: "CHERN",
    Proteins: 2,
    Fat: 0,
    Carbohydrates: 7,
    Calorie: 37,
  },
  {
    Name: "Sweet cherry",
    Proteins: 1,
    Fat: 0,
    Carbohydrates: 12,
    Calorie: 51,
  },
  {
    Name: "Blueberry",
    Proteins: 1,
    Fat: 0,
    Carbohydrates: 9,
    Calorie: 39,
  },
  {
    Name: "Prunes (dried fruits)",
    Proteins: 3,
    Fat: 0,
    Carbohydrates: 62,
    Calorie: 256,
  },
  {
    Name: "Garlic",
    Proteins: 6,
    Fat: 0,
    Carbohydrates: 23,
    Calorie: 115,
  },
  {
    Name: "The lentils are green",
    Proteins: 24,
    Fat: 2,
    Carbohydrates: 44,
    Calorie: 286,
  },
  {
    Name: "The lentils are red",
    Proteins: 22,
    Fat: 1,
    Carbohydrates: 49,
    Calorie: 312,
  },
  {
    Name: "Mulberry",
    Proteins: 1,
    Fat: 0,
    Carbohydrates: 13,
    Calorie: 52,
  },
  {
    Name: "Chocolate Gorky 75%",
    Proteins: 9,
    Fat: 41,
    Carbohydrates: 39,
    Calorie: 550,
  },
  {
    Name: "Chocolate Gorky 80%",
    Proteins: 12,
    Fat: 39,
    Carbohydrates: 34,
    Calorie: 527,
  },
  {
    Name: "Milk chocolate",
    Proteins: 7,
    Fat: 34,
    Carbohydrates: 52,
    Calorie: 539,
  },
  {
    Name: "Spinach",
    Proteins: 3,
    Fat: 0,
    Carbohydrates: 2,
    Calorie: 22,
  },
  {
    Name: "Sorrel",
    Proteins: 2,
    Fat: 0,
    Carbohydrates: 5,
    Calorie: 25,
  },
  {
    Name: "Apples",
    Proteins: 1,
    Fat: 1,
    Carbohydrates: 13,
    Calorie: 60,
  },
  {
    Name: "Dry apples (dried fruits)",
    Proteins: 3,
    Fat: 0,
    Carbohydrates: 66,
    Calorie: 269,
  },
  {
    Name: "Eggs",
    Proteins: 15,
    Fat: 13,
    Carbohydrates: 1,
    Calorie: 162,
  },
];

module.exports = en_food;
