const ru_food = [
  {
    Name: "Абрикосы",
    Proteins: 1,
    Fat: 0,
    Carbohydrates: 10,
    Calorie: 45,
  },
  {
    Name: "Авокадо",
    Proteins: 2,
    Fat: 19,
    Carbohydrates: 7,
    Calorie: 197,
  },
  {
    Name: "Аджика",
    Proteins: 2,
    Fat: 3,
    Carbohydrates: 8,
    Calorie: 59,
  },
  {
    Name: "Айва",
    Proteins: 1,
    Fat: 0,
    Carbohydrates: 9,
    Calorie: 41,
  },
  {
    Name: "Айсберг",
    Proteins: 1,
    Fat: 0,
    Carbohydrates: 2,
    Calorie: 17,
  },
  {
    Name: "Ананас",
    Proteins: 0,
    Fat: 0,
    Carbohydrates: 12,
    Calorie: 50,
  },
  {
    Name: "Ананас консервированный",
    Proteins: 0,
    Fat: 0,
    Carbohydrates: 16,
    Calorie: 65,
  },
  {
    Name: "Ананас цукаты",
    Proteins: 1,
    Fat: 2,
    Carbohydrates: 15,
    Calorie: 78,
  },
  {
    Name: "Апельсин",
    Proteins: 2,
    Fat: 0,
    Carbohydrates: 9,
    Calorie: 43,
  },
  {
    Name: "Апельсиновый сок",
    Proteins: 0,
    Fat: 0,
    Carbohydrates: 11,
    Calorie: 44,
  },
  {
    Name: "Арахис",
    Proteins: 25,
    Fat: 46,
    Carbohydrates: 13,
    Calorie: 561,
  },
  {
    Name: "Арахис в сахаре",
    Proteins: 18,
    Fat: 30,
    Carbohydrates: 51,
    Calorie: 535,
  },
  {
    Name: "Базилик свежий",
    Proteins: 3,
    Fat: 1,
    Carbohydrates: 4,
    Calorie: 27,
  },
  {
    Name: "Баклажаны",
    Proteins: 1,
    Fat: 0,
    Carbohydrates: 6,
    Calorie: 27,
  },
  {
    Name: "Банан",
    Proteins: 3,
    Fat: 3,
    Carbohydrates: 22,
    Calorie: 97,
  },
  {
    Name: "Баранина вареная",
    Proteins: 24,
    Fat: 21,
    Carbohydrates: 0,
    Calorie: 286,
  },
  {
    Name: "Батон",
    Proteins: 8,
    Fat: 3,
    Carbohydrates: 49,
    Calorie: 264,
  },
  {
    Name: "Бедро индейки",
    Proteins: 16,
    Fat: 9,
    Carbohydrates: 1,
    Calorie: 143,
  },
  {
    Name: "Бекон",
    Proteins: 15,
    Fat: 45,
    Carbohydrates: 2,
    Calorie: 469,
  },
  {
    Name: "Блины обычные",
    Proteins: 6,
    Fat: 6,
    Carbohydrates: 25,
    Calorie: 178,
  },
  {
    Name: "Борщ лёгкий",
    Proteins: 3,
    Fat: 2,
    Carbohydrates: 9,
    Calorie: 58,
  },
  {
    Name: "Брокколи",
    Proteins: 4,
    Fat: 1,
    Carbohydrates: 4,
    Calorie: 33,
  },
  {
    Name: "Брусника",
    Proteins: 1,
    Fat: 0,
    Carbohydrates: 9,
    Calorie: 42,
  },
  {
    Name: "Бульон из говядины",
    Proteins: 6,
    Fat: 4,
    Carbohydrates: 0,
    Calorie: 57,
  },
  {
    Name: "Бульон из куриной грудки",
    Proteins: 7,
    Fat: 1,
    Carbohydrates: 0,
    Calorie: 42,
  },
  {
    Name: "Бульон куриный",
    Proteins: 3,
    Fat: 2,
    Carbohydrates: 1,
    Calorie: 33,
  },
  {
    Name: "Вареная говядина",
    Proteins: 23,
    Fat: 16,
    Carbohydrates: 0,
    Calorie: 236,
  },
  {
    Name: "Вареная колбаса",
    Proteins: 12,
    Fat: 22,
    Carbohydrates: 1,
    Calorie: 253,
  },
  {
    Name: "Вареная куриная грудка",
    Proteins: 27,
    Fat: 6,
    Carbohydrates: 1,
    Calorie: 138,
  },
  {
    Name: "Вареная курица",
    Proteins: 19,
    Fat: 9,
    Carbohydrates: 0,
    Calorie: 150,
  },
  {
    Name: "Вареная морковь",
    Proteins: 1,
    Fat: 0,
    Carbohydrates: 6,
    Calorie: 31,
  },
  {
    Name: "Вареная чечевица",
    Proteins: 8,
    Fat: 0,
    Carbohydrates: 20,
    Calorie: 111,
  },
  {
    Name: "Варёная сгущёнка",
    Proteins: 7,
    Fat: 9,
    Carbohydrates: 55,
    Calorie: 326,
  },
  {
    Name: "Вермишель",
    Proteins: 11,
    Fat: 1,
    Carbohydrates: 72,
    Calorie: 347,
  },
  {
    Name: "Ветчина",
    Proteins: 16,
    Fat: 19,
    Carbohydrates: 2,
    Calorie: 246,
  },
  {
    Name: "Вино белое сухое",
    Proteins: 0,
    Fat: 0,
    Carbohydrates: 0,
    Calorie: 67,
  },
  {
    Name: "Виноград",
    Proteins: 1,
    Fat: 1,
    Carbohydrates: 16,
    Calorie: 69,
  },
  {
    Name: "Вино красное сухое",
    Proteins: 0,
    Fat: 0,
    Carbohydrates: 1,
    Calorie: 70,
  },
  {
    Name: "Вишня",
    Proteins: 1,
    Fat: 0,
    Carbohydrates: 11,
    Calorie: 54,
  },
  {
    Name: "Овсянка",
    Proteins: 12,
    Fat: 6,
    Carbohydrates: 56,
    Calorie: 327,
  },
  {
    Name: "Говядина",
    Proteins: 20,
    Fat: 13,
    Carbohydrates: 0,
    Calorie: 192,
  },
  {
    Name: "Говяжья печень",
    Proteins: 17,
    Fat: 3,
    Carbohydrates: 3,
    Calorie: 110,
  },
  {
    Name: "Голень куриная",
    Proteins: 20,
    Fat: 9,
    Carbohydrates: 0,
    Calorie: 168,
  },
  {
    Name: "Голландский сыр",
    Proteins: 24,
    Fat: 30,
    Carbohydrates: 0,
    Calorie: 373,
  },
  {
    Name: "Голубика",
    Proteins: 1,
    Fat: 1,
    Carbohydrates: 9,
    Calorie: 46,
  },
  {
    Name: "Горбуша",
    Proteins: 21,
    Fat: 7,
    Carbohydrates: 0,
    Calorie: 143,
  },
  {
    Name: "Горох",
    Proteins: 19,
    Fat: 3,
    Carbohydrates: 42,
    Calorie: 256,
  },
  {
    Name: "Гороховое пюре",
    Proteins: 8,
    Fat: 1,
    Carbohydrates: 23,
    Calorie: 106,
  },
  {
    Name: "Горошек зеленый",
    Proteins: 4,
    Fat: 0,
    Carbohydrates: 10,
    Calorie: 59,
  },
  {
    Name: "Горчица",
    Proteins: 8,
    Fat: 11,
    Carbohydrates: 13,
    Calorie: 184,
  },
  {
    Name: "Гранат",
    Proteins: 2,
    Fat: 1,
    Carbohydrates: 14,
    Calorie: 67,
  },
  {
    Name: "Грейпфрут",
    Proteins: 1,
    Fat: 0,
    Carbohydrates: 9,
    Calorie: 41,
  },
  {
    Name: "Грецкие орехи",
    Proteins: 15,
    Fat: 65,
    Carbohydrates: 14,
    Calorie: 697,
  },
  {
    Name: "Гречневая каша",
    Proteins: 5,
    Fat: 1,
    Carbohydrates: 24,
    Calorie: 131,
  },
  {
    Name: "Гречневая крупа",
    Proteins: 12,
    Fat: 4,
    Carbohydrates: 63,
    Calorie: 329,
  },
  {
    Name: "Грибы белые",
    Proteins: 9,
    Fat: 2,
    Carbohydrates: 3,
    Calorie: 28,
  },
  {
    Name: "Грибы белые сушеные",
    Proteins: 27,
    Fat: 7,
    Carbohydrates: 16,
    Calorie: 239,
  },
  {
    Name: "Грибы грузди",
    Proteins: 2,
    Fat: 1,
    Carbohydrates: 1,
    Calorie: 16,
  },
  {
    Name: "Грибы лисички",
    Proteins: 2,
    Fat: 1,
    Carbohydrates: 1,
    Calorie: 20,
  },
  {
    Name: "Грибы шампиньоны",
    Proteins: 4,
    Fat: 1,
    Carbohydrates: 0,
    Calorie: 22,
  },
  {
    Name: "Груша",
    Proteins: 1,
    Fat: 0,
    Carbohydrates: 12,
    Calorie: 51,
  },
  {
    Name: "Груша (сухофрукты)",
    Proteins: 2,
    Fat: 0,
    Carbohydrates: 62,
    Calorie: 246,
  },
  {
    Name: "Джем мандариновый",
    Proteins: 0,
    Fat: 0,
    Carbohydrates: 72,
    Calorie: 276,
  },
  {
    Name: "Дрожжи",
    Proteins: 29,
    Fat: 3,
    Carbohydrates: 23,
    Calorie: 263,
  },
  {
    Name: "Дрожжи сухие",
    Proteins: 49,
    Fat: 6,
    Carbohydrates: 40,
    Calorie: 410,
  },
  {
    Name: "Дыня",
    Proteins: 1,
    Fat: 0,
    Carbohydrates: 8,
    Calorie: 35,
  },
  {
    Name: "Ежевика",
    Proteins: 2,
    Fat: 0,
    Carbohydrates: 5,
    Calorie: 31,
  },
  {
    Name: "Жареное яйцо",
    Proteins: 14,
    Fat: 14,
    Carbohydrates: 1,
    Calorie: 183,
  },
  {
    Name: "Желатин",
    Proteins: 86,
    Fat: 0,
    Carbohydrates: 1,
    Calorie: 343,
  },
  {
    Name: "Зеленая фасоль",
    Proteins: 3,
    Fat: 0,
    Carbohydrates: 4,
    Calorie: 30,
  },
  {
    Name: "Зеленый лук",
    Proteins: 1,
    Fat: 0,
    Carbohydrates: 4,
    Calorie: 19,
  },
  {
    Name: "Зелень петрушки",
    Proteins: 4,
    Fat: 0,
    Carbohydrates: 8,
    Calorie: 50,
  },
  {
    Name: "Зелёный горошек 'Бондюэль'",
    Proteins: 5,
    Fat: 0,
    Carbohydrates: 8,
    Calorie: 60,
  },
  {
    Name: "Зелёный горошек 'Фрау Марта'",
    Proteins: 3,
    Fat: 0,
    Carbohydrates: 7,
    Calorie: 40,
  },
  {
    Name: "Земляника",
    Proteins: 1,
    Fat: 0,
    Carbohydrates: 9,
    Calorie: 38,
  },
  {
    Name: "Зефир",
    Proteins: 1,
    Fat: 0,
    Carbohydrates: 80,
    Calorie: 304,
  },
  {
    Name: "Изюм",
    Proteins: 2,
    Fat: 0,
    Carbohydrates: 68,
    Calorie: 280,
  },
  {
    Name: "Имбирь свежий",
    Proteins: 2,
    Fat: 1,
    Carbohydrates: 16,
    Calorie: 72,
  },
  {
    Name: "Индейка (грудка)",
    Proteins: 19,
    Fat: 2,
    Carbohydrates: 0,
    Calorie: 94,
  },
  {
    Name: "Индейка (филе)",
    Proteins: 20,
    Fat: 12,
    Carbohydrates: 0,
    Calorie: 188,
  },
  {
    Name: "Инжир (сухофрукты)",
    Proteins: 3,
    Fat: 1,
    Carbohydrates: 57,
    Calorie: 239,
  },
  {
    Name: "Йогурт",
    Proteins: 4,
    Fat: 3,
    Carbohydrates: 11,
    Calorie: 97,
  },
  {
    Name: "Кабачки жареные",
    Proteins: 1,
    Fat: 6,
    Carbohydrates: 7,
    Calorie: 91,
  },
  {
    Name: "Цукини",
    Proteins: 2,
    Fat: 0,
    Carbohydrates: 3,
    Calorie: 16,
  },
  {
    Name: "Кабачковая икра",
    Proteins: 1,
    Fat: 6,
    Carbohydrates: 7,
    Calorie: 90,
  },
  {
    Name: "Кабачок",
    Proteins: 1,
    Fat: 1,
    Carbohydrates: 5,
    Calorie: 28,
  },
  {
    Name: "Какао",
    Proteins: 14,
    Fat: 9,
    Carbohydrates: 26,
    Calorie: 234,
  },
  {
    Name: "Какао порошок",
    Proteins: 23,
    Fat: 15,
    Carbohydrates: 29,
    Calorie: 326,
  },
  {
    Name: "Кальмар",
    Proteins: 18,
    Fat: 2,
    Carbohydrates: 1,
    Calorie: 97,
  },
  {
    Name: "Кальмар вареный",
    Proteins: 18,
    Fat: 3,
    Carbohydrates: 1,
    Calorie: 103,
  },
  {
    Name: "Каперсы",
    Proteins: 2,
    Fat: 1,
    Carbohydrates: 4,
    Calorie: 21,
  },
  {
    Name: "Капуста белокочаная",
    Proteins: 2,
    Fat: 0,
    Carbohydrates: 5,
    Calorie: 28,
  },
  {
    Name: "Капуста брокколи замороженая",
    Proteins: 2,
    Fat: 0,
    Carbohydrates: 4,
    Calorie: 21,
  },
  {
    Name: "Капуста брюссельская",
    Proteins: 4,
    Fat: 0,
    Carbohydrates: 4,
    Calorie: 47,
  },
  {
    Name: "Капуста жареная",
    Proteins: 3,
    Fat: 6,
    Carbohydrates: 8,
    Calorie: 88,
  },
  {
    Name: "Капуста квашенная",
    Proteins: 2,
    Fat: 0,
    Carbohydrates: 3,
    Calorie: 23,
  },
  {
    Name: "Капуста кольраби",
    Proteins: 3,
    Fat: 0,
    Carbohydrates: 9,
    Calorie: 42,
  },
  {
    Name: "Капуста краснокочанная",
    Proteins: 2,
    Fat: 0,
    Carbohydrates: 6,
    Calorie: 29,
  },
  {
    Name: "Капуста морская",
    Proteins: 1,
    Fat: 5,
    Carbohydrates: 0,
    Calorie: 58,
  },
  {
    Name: "Капуста пекинская",
    Proteins: 2,
    Fat: 0,
    Carbohydrates: 3,
    Calorie: 15,
  },
  {
    Name: "Капуста цветная",
    Proteins: 3,
    Fat: 0,
    Carbohydrates: 5,
    Calorie: 34,
  },
  {
    Name: "Картофель",
    Proteins: 2,
    Fat: 1,
    Carbohydrates: 20,
    Calorie: 84,
  },
  {
    Name: "Картофель молодой",
    Proteins: 2,
    Fat: 0,
    Carbohydrates: 16,
    Calorie: 61,
  },
  {
    Name: "Картофельные хлопья",
    Proteins: 8,
    Fat: 1,
    Carbohydrates: 83,
    Calorie: 366,
  },
  {
    Name: "Картофель отварной",
    Proteins: 2,
    Fat: 1,
    Carbohydrates: 16,
    Calorie: 83,
  },
  {
    Name: "Картофель печеный",
    Proteins: 3,
    Fat: 3,
    Carbohydrates: 22,
    Calorie: 113,
  },
  {
    Name: "Картофель фри",
    Proteins: 4,
    Fat: 17,
    Carbohydrates: 40,
    Calorie: 323,
  },
  {
    Name: "Каша рисовая",
    Proteins: 2,
    Fat: 3,
    Carbohydrates: 26,
    Calorie: 130,
  },
  {
    Name: "Квас хлебный",
    Proteins: 0,
    Fat: 0,
    Carbohydrates: 5,
    Calorie: 24,
  },
  {
    Name: "Кедровые орехи",
    Proteins: 15,
    Fat: 63,
    Carbohydrates: 17,
    Calorie: 652,
  },
  {
    Name: "Кетчуп",
    Proteins: 5,
    Fat: 1,
    Carbohydrates: 16,
    Calorie: 90,
  },
  {
    Name: "Кефир 1%",
    Proteins: 3,
    Fat: 1,
    Carbohydrates: 5,
    Calorie: 45,
  },
  {
    Name: "Кефир 2,5%",
    Proteins: 3,
    Fat: 3,
    Carbohydrates: 4,
    Calorie: 52,
  },
  {
    Name: "Кефир 3,2%",
    Proteins: 3,
    Fat: 3,
    Carbohydrates: 4,
    Calorie: 58,
  },
  {
    Name: "Кешью",
    Proteins: 21,
    Fat: 48,
    Carbohydrates: 20,
    Calorie: 607,
  },
  {
    Name: "Киви",
    Proteins: 1,
    Fat: 1,
    Carbohydrates: 10,
    Calorie: 51,
  },
  {
    Name: "Клубника",
    Proteins: 1,
    Fat: 0,
    Carbohydrates: 7,
    Calorie: 32,
  },
  {
    Name: "Клюква",
    Proteins: 0,
    Fat: 0,
    Carbohydrates: 9,
    Calorie: 43,
  },
  {
    Name: "Клюква сушеная",
    Proteins: 0,
    Fat: 1,
    Carbohydrates: 70,
    Calorie: 305,
  },
  {
    Name: "Козий сыр",
    Proteins: 19,
    Fat: 23,
    Carbohydrates: 2,
    Calorie: 296,
  },
  {
    Name: "Корень имбиря",
    Proteins: 2,
    Fat: 1,
    Carbohydrates: 18,
    Calorie: 90,
  },
  {
    Name: "Корень сельдерея",
    Proteins: 1,
    Fat: 0,
    Carbohydrates: 6,
    Calorie: 31,
  },
  {
    Name: "Коричневый сахар",
    Proteins: 0,
    Fat: 0,
    Carbohydrates: 92,
    Calorie: 393,
  },
  {
    Name: "Корнишоны маринованные",
    Proteins: 1,
    Fat: 0,
    Carbohydrates: 4,
    Calorie: 36,
  },
  {
    Name: "Котлети",
    Proteins: 26,
    Fat: 32,
    Carbohydrates: 6,
    Calorie: 415,
  },
  {
    Name: "Кофе молотый Арабика",
    Proteins: 12,
    Fat: 14,
    Carbohydrates: 3,
    Calorie: 193,
  },
  {
    Name: "Кофе растворимый (сухой)",
    Proteins: 15,
    Fat: 4,
    Carbohydrates: 7,
    Calorie: 116,
  },
  {
    Name: "Кофе эспрессо крепкий",
    Proteins: 1,
    Fat: 2,
    Carbohydrates: 0,
    Calorie: 19,
  },
  {
    Name: "Крабовые палочки",
    Proteins: 8,
    Fat: 2,
    Carbohydrates: 10,
    Calorie: 85,
  },
  {
    Name: "Краковская колбаса",
    Proteins: 17,
    Fat: 39,
    Carbohydrates: 0,
    Calorie: 420,
  },
  {
    Name: "Красная фасоль консервированная",
    Proteins: 7,
    Fat: 0,
    Carbohydrates: 17,
    Calorie: 99,
  },
  {
    Name: "Крахмал картофельный",
    Proteins: 0,
    Fat: 0,
    Carbohydrates: 82,
    Calorie: 335,
  },
  {
    Name: "Крахмал кукурузный",
    Proteins: 1,
    Fat: 0,
    Carbohydrates: 87,
    Calorie: 348,
  },
  {
    Name: "Креветки (отварные)",
    Proteins: 18,
    Fat: 2,
    Carbohydrates: 0,
    Calorie: 90,
  },
  {
    Name: "Крупа гречневая",
    Proteins: 12,
    Fat: 3,
    Carbohydrates: 65,
    Calorie: 326,
  },
  {
    Name: "Крупа кукурузная",
    Proteins: 8,
    Fat: 1,
    Carbohydrates: 75,
    Calorie: 337,
  },
  {
    Name: "Крупа манная",
    Proteins: 11,
    Fat: 1,
    Carbohydrates: 70,
    Calorie: 330,
  },
  {
    Name: "Крупа перловая",
    Proteins: 10,
    Fat: 1,
    Carbohydrates: 65,
    Calorie: 328,
  },
  {
    Name: "Крупа пшеничная",
    Proteins: 12,
    Fat: 2,
    Carbohydrates: 63,
    Calorie: 322,
  },
  {
    Name: "Крупа рисовая",
    Proteins: 7,
    Fat: 11,
    Carbohydrates: 63,
    Calorie: 330,
  },
  {
    Name: "Крупа ячневая",
    Proteins: 10,
    Fat: 1,
    Carbohydrates: 59,
    Calorie: 318,
  },
  {
    Name: "Крыжовник",
    Proteins: 1,
    Fat: 0,
    Carbohydrates: 10,
    Calorie: 41,
  },
  {
    Name: "Кукуруза консервированная",
    Proteins: 3,
    Fat: 2,
    Carbohydrates: 17,
    Calorie: 87,
  },
  {
    Name: "Кукурузные хлопья",
    Proteins: 6,
    Fat: 3,
    Carbohydrates: 73,
    Calorie: 353,
  },
  {
    Name: "Кунжут",
    Proteins: 20,
    Fat: 50,
    Carbohydrates: 11,
    Calorie: 562,
  },
  {
    Name: "Курага",
    Proteins: 5,
    Fat: 0,
    Carbohydrates: 54,
    Calorie: 232,
  },
  {
    Name: "Куриная печень",
    Proteins: 19,
    Fat: 7,
    Carbohydrates: 1,
    Calorie: 140,
  },
  {
    Name: "Куриные грудки",
    Proteins: 23,
    Fat: 6,
    Carbohydrates: 3,
    Calorie: 144,
  },
  {
    Name: "Куриные окорочка",
    Proteins: 18,
    Fat: 11,
    Carbohydrates: 0,
    Calorie: 170,
  },
  {
    Name: "Курица",
    Proteins: 21,
    Fat: 11,
    Carbohydrates: 1,
    Calorie: 186,
  },
  {
    Name: "Кус-Кус (крупа)",
    Proteins: 13,
    Fat: 1,
    Carbohydrates: 77,
    Calorie: 373,
  },
  {
    Name: "Лаваш грузинский",
    Proteins: 8,
    Fat: 2,
    Carbohydrates: 53,
    Calorie: 269,
  },
  {
    Name: "Лайм",
    Proteins: 1,
    Fat: 0,
    Carbohydrates: 4,
    Calorie: 20,
  },
  {
    Name: "Лапша гречневая",
    Proteins: 15,
    Fat: 1,
    Carbohydrates: 71,
    Calorie: 348,
  },
  {
    Name: "Лапша рисовая",
    Proteins: 5,
    Fat: 1,
    Carbohydrates: 81,
    Calorie: 350,
  },
  {
    Name: "Лапша яичная",
    Proteins: 10,
    Fat: 2,
    Carbohydrates: 64,
    Calorie: 330,
  },
  {
    Name: "Лимон",
    Proteins: 1,
    Fat: 0,
    Carbohydrates: 4,
    Calorie: 27,
  },
  {
    Name: "Лимонный сок",
    Proteins: 1,
    Fat: 0,
    Carbohydrates: 4,
    Calorie: 20,
  },
  {
    Name: "Лосось",
    Proteins: 21,
    Fat: 10,
    Carbohydrates: 1,
    Calorie: 172,
  },
  {
    Name: "Лук",
    Proteins: 1,
    Fat: 0,
    Carbohydrates: 9,
    Calorie: 40,
  },
  {
    Name: "Лук зелёный перо",
    Proteins: 1,
    Fat: 0,
    Carbohydrates: 5,
    Calorie: 16,
  },
  {
    Name: "Лук красный салатный",
    Proteins: 1,
    Fat: 0,
    Carbohydrates: 9,
    Calorie: 42,
  },
  {
    Name: "Льняное масло",
    Proteins: 1,
    Fat: 92,
    Carbohydrates: 4,
    Calorie: 849,
  },
  {
    Name: "Майонез",
    Proteins: 2,
    Fat: 57,
    Carbohydrates: 4,
    Calorie: 550,
  },
  {
    Name: "Майонез 15%",
    Proteins: 0,
    Fat: 15,
    Carbohydrates: 5,
    Calorie: 156,
  },
  {
    Name: "Майонез провансаль 67%",
    Proteins: 3,
    Fat: 369,
    Carbohydrates: 25,
    Calorie: 619,
  },
  {
    Name: "Мак",
    Proteins: 17,
    Fat: 46,
    Carbohydrates: 8,
    Calorie: 519,
  },
  {
    Name: "Макаронные изделия",
    Proteins: 10,
    Fat: 0,
    Carbohydrates: 72,
    Calorie: 344,
  },
  {
    Name: "Макароны отварные",
    Proteins: 4,
    Fat: 1,
    Carbohydrates: 23,
    Calorie: 119,
  },
  {
    Name: "Малина",
    Proteins: 4,
    Fat: 0,
    Carbohydrates: 9,
    Calorie: 41,
  },
  {
    Name: "Манго",
    Proteins: 1,
    Fat: 0,
    Carbohydrates: 13,
    Calorie: 62,
  },
  {
    Name: "Манго цукаты",
    Proteins: 0,
    Fat: 0,
    Carbohydrates: 60,
    Calorie: 278,
  },
  {
    Name: "Мандарин",
    Proteins: 1,
    Fat: 1,
    Carbohydrates: 9,
    Calorie: 40,
  },
  {
    Name: "Мармелад",
    Proteins: 1,
    Fat: 0,
    Carbohydrates: 75,
    Calorie: 302,
  },
  {
    Name: "Маслины",
    Proteins: 1,
    Fat: 14,
    Carbohydrates: 10,
    Calorie: 167,
  },
  {
    Name: "Маслины без косточки",
    Proteins: 1,
    Fat: 13,
    Carbohydrates: 2,
    Calorie: 133,
  },
  {
    Name: "Масло кукурузное",
    Proteins: 1,
    Fat: 101,
    Carbohydrates: 0,
    Calorie: 916,
  },
  {
    Name: "Масло льняное",
    Proteins: 0,
    Fat: 96,
    Carbohydrates: 0,
    Calorie: 895,
  },
  {
    Name: "Масло оливковое",
    Proteins: 1,
    Fat: 91,
    Carbohydrates: 3,
    Calorie: 851,
  },
  {
    Name: "Масло подсолнечное",
    Proteins: 0,
    Fat: 96,
    Carbohydrates: 0,
    Calorie: 864,
  },
  {
    Name: "Масло растительное",
    Proteins: 2,
    Fat: 97,
    Carbohydrates: 0,
    Calorie: 897,
  },
  {
    Name: "Масло сливочное",
    Proteins: 1,
    Fat: 74,
    Carbohydrates: 1,
    Calorie: 674,
  },
  {
    Name: "Масло топленое",
    Proteins: 0,
    Fat: 86,
    Carbohydrates: 0,
    Calorie: 890,
  },
  {
    Name: "Мед",
    Proteins: 1,
    Fat: 0,
    Carbohydrates: 80,
    Calorie: 315,
  },
  {
    Name: "Миндаль",
    Proteins: 18,
    Fat: 51,
    Carbohydrates: 16,
    Calorie: 601,
  },
  {
    Name: "Молоко",
    Proteins: 7,
    Fat: 3,
    Carbohydrates: 7,
    Calorie: 66,
  },
  {
    Name: "Молоко 0,5%",
    Proteins: 2,
    Fat: 1,
    Carbohydrates: 3,
    Calorie: 35,
  },
  {
    Name: "Молоко 1,5%",
    Proteins: 3,
    Fat: 2,
    Carbohydrates: 5,
    Calorie: 44,
  },
  {
    Name: "Молоко 2,5%",
    Proteins: 3,
    Fat: 3,
    Carbohydrates: 7,
    Calorie: 64,
  },
  {
    Name: "Молоко 3,2%",
    Proteins: 3,
    Fat: 3,
    Carbohydrates: 8,
    Calorie: 67,
  },
  {
    Name: "Молоко сгущёное",
    Proteins: 7,
    Fat: 9,
    Carbohydrates: 56,
    Calorie: 317,
  },
  {
    Name: "Молоко сухое",
    Proteins: 31,
    Fat: 22,
    Carbohydrates: 36,
    Calorie: 446,
  },
  {
    Name: "Морковь отварная",
    Proteins: 1,
    Fat: 0,
    Carbohydrates: 7,
    Calorie: 32,
  },
  {
    Name: "Морковь печеная",
    Proteins: 1,
    Fat: 0,
    Carbohydrates: 7,
    Calorie: 31,
  },
  {
    Name: "Морковь свежая",
    Proteins: 1,
    Fat: 0,
    Carbohydrates: 8,
    Calorie: 35,
  },
  {
    Name: "Мука кукурузная",
    Proteins: 9,
    Fat: 3,
    Carbohydrates: 65,
    Calorie: 333,
  },
  {
    Name: "Мука пшеничная в/с",
    Proteins: 10,
    Fat: 1,
    Carbohydrates: 71,
    Calorie: 332,
  },
  {
    Name: "Мука ржаная",
    Proteins: 8,
    Fat: 2,
    Carbohydrates: 65,
    Calorie: 307,
  },
  {
    Name: "Мюстли с фруктами",
    Proteins: 8,
    Fat: 2,
    Carbohydrates: 68,
    Calorie: 314,
  },
  {
    Name: "Мясо свинина",
    Proteins: 26,
    Fat: 29,
    Carbohydrates: 7,
    Calorie: 293,
  },
  {
    Name: "Мясо свинина постная",
    Proteins: 18,
    Fat: 8,
    Carbohydrates: 0,
    Calorie: 151,
  },
  {
    Name: "Нектарин",
    Proteins: 1,
    Fat: 0,
    Carbohydrates: 11,
    Calorie: 47,
  },
  {
    Name: "Облепиха",
    Proteins: 1,
    Fat: 2,
    Carbohydrates: 6,
    Calorie: 47,
  },
  {
    Name: "Огурцы",
    Proteins: 1,
    Fat: 0,
    Carbohydrates: 4,
    Calorie: 19,
  },
  {
    Name: "Огурцы грунтовые",
    Proteins: 1,
    Fat: 0,
    Carbohydrates: 3,
    Calorie: 14,
  },
  {
    Name: "Огурцы маринованные",
    Proteins: 2,
    Fat: 0,
    Carbohydrates: 2,
    Calorie: 16,
  },
  {
    Name: "Огурцы солёные",
    Proteins: 1,
    Fat: 0,
    Carbohydrates: 2,
    Calorie: 14,
  },
  {
    Name: "Оливки",
    Proteins: 1,
    Fat: 17,
    Carbohydrates: 5,
    Calorie: 178,
  },
  {
    Name: "Оливки зеленые без косточки",
    Proteins: 1,
    Fat: 17,
    Carbohydrates: 0,
    Calorie: 157,
  },
  {
    Name: "Омлет",
    Proteins: 10,
    Fat: 14,
    Carbohydrates: 3,
    Calorie: 175,
  },
  {
    Name: "Паприка",
    Proteins: 3,
    Fat: 2,
    Carbohydrates: 7,
    Calorie: 112,
  },
  {
    Name: "Патиссон",
    Proteins: 1,
    Fat: 0,
    Carbohydrates: 4,
    Calorie: 19,
  },
  {
    Name: "Перепелиное яйцо",
    Proteins: 13,
    Fat: 13,
    Carbohydrates: 0,
    Calorie: 167,
  },
  {
    Name: "Перец сладкий",
    Proteins: 1,
    Fat: 0,
    Carbohydrates: 5,
    Calorie: 26,
  },
  {
    Name: "Перец чили",
    Proteins: 2,
    Fat: 0,
    Carbohydrates: 9,
    Calorie: 40,
  },
  {
    Name: "Персики",
    Proteins: 1,
    Fat: 1,
    Carbohydrates: 12,
    Calorie: 51,
  },
  {
    Name: "Персики (сухофрукты)",
    Proteins: 2,
    Fat: 0,
    Carbohydrates: 42,
    Calorie: 168,
  },
  {
    Name: "Петрушка корень",
    Proteins: 2,
    Fat: 0,
    Carbohydrates: 11,
    Calorie: 48,
  },
  {
    Name: "Петрушка свежая",
    Proteins: 3,
    Fat: 1,
    Carbohydrates: 7,
    Calorie: 38,
  },
  {
    Name: "Печень куриная",
    Proteins: 27,
    Fat: 7,
    Carbohydrates: 1,
    Calorie: 144,
  },
  {
    Name: "Пиво светлое",
    Proteins: 0,
    Fat: 0,
    Carbohydrates: 4,
    Calorie: 50,
  },
  {
    Name: "Плавленный сыр",
    Proteins: 15,
    Fat: 20,
    Carbohydrates: 2,
    Calorie: 280,
  },
  {
    Name: "Помидоры консервированные",
    Proteins: 1,
    Fat: 0,
    Carbohydrates: 5,
    Calorie: 23,
  },
  {
    Name: "Помидоры свежие",
    Proteins: 4,
    Fat: 1,
    Carbohydrates: 3,
    Calorie: 33,
  },
  {
    Name: "Пшено",
    Proteins: 11,
    Fat: 3,
    Carbohydrates: 68,
    Calorie: 337,
  },
  {
    Name: "Ревень черешковый",
    Proteins: 1,
    Fat: 0,
    Carbohydrates: 4,
    Calorie: 16,
  },
  {
    Name: "Редис",
    Proteins: 1,
    Fat: 0,
    Carbohydrates: 4,
    Calorie: 20,
  },
  {
    Name: "Редька",
    Proteins: 2,
    Fat: 0,
    Carbohydrates: 7,
    Calorie: 35,
  },
  {
    Name: "Редька зеленая",
    Proteins: 2,
    Fat: 0,
    Carbohydrates: 7,
    Calorie: 35,
  },
  {
    Name: "Репа",
    Proteins: 1,
    Fat: 0,
    Carbohydrates: 5,
    Calorie: 29,
  },
  {
    Name: "Рис",
    Proteins: 7,
    Fat: 1,
    Carbohydrates: 75,
    Calorie: 331,
  },
  {
    Name: "Рожки отварные",
    Proteins: 3,
    Fat: 0,
    Carbohydrates: 24,
    Calorie: 115,
  },
  {
    Name: "Руккола",
    Proteins: 2,
    Fat: 1,
    Carbohydrates: 2,
    Calorie: 24,
  },
  {
    Name: "Рыба скумбрия",
    Proteins: 16,
    Fat: 13,
    Carbohydrates: 1,
    Calorie: 187,
  },
  {
    Name: "Рыба треска",
    Proteins: 17,
    Fat: 1,
    Carbohydrates: 0,
    Calorie: 80,
  },
  {
    Name: "Салат лист",
    Proteins: 1,
    Fat: 0,
    Carbohydrates: 2,
    Calorie: 16,
  },
  {
    Name: "Сахар песок",
    Proteins: 0,
    Fat: 0,
    Carbohydrates: 109,
    Calorie: 396,
  },
  {
    Name: "Свежая капуста",
    Proteins: 2,
    Fat: 0,
    Carbohydrates: 5,
    Calorie: 25,
  },
  {
    Name: "Свежий укроп",
    Proteins: 3,
    Fat: 1,
    Carbohydrates: 6,
    Calorie: 38,
  },
  {
    Name: "Свекла",
    Proteins: 2,
    Fat: 1,
    Carbohydrates: 12,
    Calorie: 61,
  },
  {
    Name: "Свекла отварная",
    Proteins: 2,
    Fat: 0,
    Carbohydrates: 10,
    Calorie: 50,
  },
  {
    Name: "Сельдерей",
    Proteins: 1,
    Fat: 0,
    Carbohydrates: 3,
    Calorie: 13,
  },
  {
    Name: "Сельдерей стебель",
    Proteins: 1,
    Fat: 0,
    Carbohydrates: 2,
    Calorie: 11,
  },
  {
    Name: "Сельдь атлантическая жирная",
    Proteins: 15,
    Fat: 15,
    Carbohydrates: 0,
    Calorie: 204,
  },
  {
    Name: "Семена тыквы неочищенные с солью",
    Proteins: 29,
    Fat: 47,
    Carbohydrates: 13,
    Calorie: 596,
  },
  {
    Name: "Семечки подсолнечные",
    Proteins: 26,
    Fat: 50,
    Carbohydrates: 9,
    Calorie: 583,
  },
  {
    Name: "Сладкая кукуруза в початках",
    Proteins: 4,
    Fat: 3,
    Carbohydrates: 21,
    Calorie: 124,
  },
  {
    Name: "Сливки 10%",
    Proteins: 3,
    Fat: 10,
    Carbohydrates: 4,
    Calorie: 118,
  },
  {
    Name: "Сливки 20%",
    Proteins: 3,
    Fat: 20,
    Carbohydrates: 4,
    Calorie: 206,
  },
  {
    Name: "Сливки 22%",
    Proteins: 3,
    Fat: 22,
    Carbohydrates: 4,
    Calorie: 224,
  },
  {
    Name: "Сливки 33%",
    Proteins: 2,
    Fat: 33,
    Carbohydrates: 4,
    Calorie: 322,
  },
  {
    Name: "Смесь орехов и сухофруктов экзотик",
    Proteins: 8,
    Fat: 26,
    Carbohydrates: 52,
    Calorie: 466,
  },
  {
    Name: "Сметана 10 %",
    Proteins: 3,
    Fat: 10,
    Carbohydrates: 4,
    Calorie: 117,
  },
  {
    Name: "Сметана 15%",
    Proteins: 3,
    Fat: 15,
    Carbohydrates: 4,
    Calorie: 159,
  },
  {
    Name: "Сметана 20%",
    Proteins: 3,
    Fat: 19,
    Carbohydrates: 6,
    Calorie: 204,
  },
  {
    Name: "Сметана 30 %",
    Proteins: 2,
    Fat: 30,
    Carbohydrates: 3,
    Calorie: 291,
  },
  {
    Name: "Смородина красная",
    Proteins: 1,
    Fat: 0,
    Carbohydrates: 8,
    Calorie: 40,
  },
  {
    Name: "Смородина чёрная",
    Proteins: 1,
    Fat: 0,
    Carbohydrates: 9,
    Calorie: 41,
  },
  {
    Name: "Соевый соус",
    Proteins: 5,
    Fat: 0,
    Carbohydrates: 22,
    Calorie: 36,
  },
  {
    Name: "Сок апельсиновый",
    Proteins: 1,
    Fat: 0,
    Carbohydrates: 11,
    Calorie: 47,
  },
  {
    Name: "Сок грейпфрутовый",
    Proteins: 0,
    Fat: 0,
    Carbohydrates: 10,
    Calorie: 44,
  },
  {
    Name: "Сок лайма",
    Proteins: 1,
    Fat: 0,
    Carbohydrates: 6,
    Calorie: 22,
  },
  {
    Name: "Сок лимонный",
    Proteins: 1,
    Fat: 0,
    Carbohydrates: 5,
    Calorie: 29,
  },
  {
    Name: "Сок мандарина",
    Proteins: 1,
    Fat: 0,
    Carbohydrates: 10,
    Calorie: 43,
  },
  {
    Name: "Сок свекольный",
    Proteins: 1,
    Fat: 0,
    Carbohydrates: 14,
    Calorie: 61,
  },
  {
    Name: "Сок томатный",
    Proteins: 0,
    Fat: 0,
    Carbohydrates: 5,
    Calorie: 21,
  },
  {
    Name: "Сок яблочный",
    Proteins: 0,
    Fat: 0,
    Carbohydrates: 10,
    Calorie: 44,
  },
  {
    Name: "Соленый огурец",
    Proteins: 1,
    Fat: 0,
    Carbohydrates: 3,
    Calorie: 14,
  },
  {
    Name: "Соус соевый",
    Proteins: 4,
    Fat: 0,
    Carbohydrates: 10,
    Calorie: 53,
  },
  {
    Name: "Соя",
    Proteins: 34,
    Fat: 12,
    Carbohydrates: 27,
    Calorie: 359,
  },
  {
    Name: "Спагетти отварные",
    Proteins: 7,
    Fat: 1,
    Carbohydrates: 46,
    Calorie: 223,
  },
  {
    Name: "Спагетти (сухой продукт)",
    Proteins: 10,
    Fat: 1,
    Carbohydrates: 72,
    Calorie: 344,
  },
  {
    Name: "Сухари панировочные",
    Proteins: 12,
    Fat: 2,
    Carbohydrates: 74,
    Calorie: 362,
  },
  {
    Name: "Сыворотка",
    Proteins: 1,
    Fat: 0,
    Carbohydrates: 4,
    Calorie: 22,
  },
  {
    Name: "Сыр 45%",
    Proteins: 26,
    Fat: 26,
    Carbohydrates: 0,
    Calorie: 336,
  },
  {
    Name: "Сыр Адыгейский",
    Proteins: 18,
    Fat: 16,
    Carbohydrates: 0,
    Calorie: 224,
  },
  {
    Name: "Сыр гауда",
    Proteins: 24,
    Fat: 27,
    Carbohydrates: 2,
    Calorie: 350,
  },
  {
    Name: "Сыр 'российский'",
    Proteins: 23,
    Fat: 29,
    Carbohydrates: 0,
    Calorie: 361,
  },
  {
    Name: "Сыр твердый",
    Proteins: 25,
    Fat: 27,
    Carbohydrates: 2,
    Calorie: 358,
  },
  {
    Name: "Творог 0%",
    Proteins: 16,
    Fat: 0,
    Carbohydrates: 2,
    Calorie: 75,
  },
  {
    Name: "Творог 1%",
    Proteins: 17,
    Fat: 1,
    Carbohydrates: 2,
    Calorie: 82,
  },
  {
    Name: "Творог 10%",
    Proteins: 15,
    Fat: 9,
    Carbohydrates: 2,
    Calorie: 150,
  },
  {
    Name: "Творог 5 %",
    Proteins: 17,
    Fat: 5,
    Carbohydrates: 2,
    Calorie: 122,
  },
  {
    Name: "Творог 9%",
    Proteins: 16,
    Fat: 8,
    Carbohydrates: 3,
    Calorie: 153,
  },
  {
    Name: "Творожная масса с цукатами",
    Proteins: 7,
    Fat: 21,
    Carbohydrates: 33,
    Calorie: 349,
  },
  {
    Name: "Тесто дрожжевое",
    Proteins: 7,
    Fat: 4,
    Carbohydrates: 43,
    Calorie: 238,
  },
  {
    Name: "Томат",
    Proteins: 1,
    Fat: 0,
    Carbohydrates: 5,
    Calorie: 27,
  },
  {
    Name: "Томатная паста помидорка",
    Proteins: 1,
    Fat: 0,
    Carbohydrates: 15,
    Calorie: 77,
  },
  {
    Name: "Томатный сок",
    Proteins: 1,
    Fat: 0,
    Carbohydrates: 4,
    Calorie: 25,
  },
  {
    Name: "Томаты черри",
    Proteins: 1,
    Fat: 0,
    Carbohydrates: 3,
    Calorie: 17,
  },
  {
    Name: "Треска филе",
    Proteins: 17,
    Fat: 1,
    Carbohydrates: 0,
    Calorie: 78,
  },
  {
    Name: "Тыква",
    Proteins: 1,
    Fat: 0,
    Carbohydrates: 5,
    Calorie: 22,
  },
  {
    Name: "Укроп",
    Proteins: 3,
    Fat: 1,
    Carbohydrates: 6,
    Calorie: 38,
  },
  {
    Name: "Уксус столовый 6-7%",
    Proteins: 0,
    Fat: 0,
    Carbohydrates: 6,
    Calorie: 13,
  },
  {
    Name: "Фарш говяжий",
    Proteins: 18,
    Fat: 16,
    Carbohydrates: 0,
    Calorie: 214,
  },
  {
    Name: "Фарш куриный",
    Proteins: 19,
    Fat: 10,
    Carbohydrates: 0,
    Calorie: 166,
  },
  {
    Name: "Фасоль",
    Proteins: 18,
    Fat: 1,
    Carbohydrates: 44,
    Calorie: 263,
  },
  {
    Name: "Фенхель",
    Proteins: 1,
    Fat: 0,
    Carbohydrates: 7,
    Calorie: 31,
  },
  {
    Name: "Филе куринное",
    Proteins: 23,
    Fat: 2,
    Carbohydrates: 0,
    Calorie: 114,
  },
  {
    Name: "Филе куриной грудки",
    Proteins: 22,
    Fat: 2,
    Carbohydrates: 0,
    Calorie: 109,
  },
  {
    Name: "Финики (сухофрукты)",
    Proteins: 2,
    Fat: 0,
    Carbohydrates: 72,
    Calorie: 280,
  },
  {
    Name: "Фруктоза",
    Proteins: 0,
    Fat: 0,
    Carbohydrates: 100,
    Calorie: 390,
  },
  {
    Name: "Фундук",
    Proteins: 15,
    Fat: 62,
    Carbohydrates: 11,
    Calorie: 665,
  },
  {
    Name: "Хлеб белый",
    Proteins: 8,
    Fat: 3,
    Carbohydrates: 54,
    Calorie: 254,
  },
  {
    Name: "Хлеб 'бородинский'",
    Proteins: 7,
    Fat: 1,
    Carbohydrates: 42,
    Calorie: 210,
  },
  {
    Name: "Хлеб пшеничный",
    Proteins: 8,
    Fat: 3,
    Carbohydrates: 50,
    Calorie: 263,
  },
  {
    Name: "Хлеб ржаной",
    Proteins: 7,
    Fat: 1,
    Carbohydrates: 36,
    Calorie: 187,
  },
  {
    Name: "Хлебцы пшеничные",
    Proteins: 12,
    Fat: 2,
    Carbohydrates: 60,
    Calorie: 305,
  },
  {
    Name: "Хлопья кукурузные",
    Proteins: 7,
    Fat: 1,
    Carbohydrates: 84,
    Calorie: 373,
  },
  {
    Name: "Хлопья овсяные",
    Proteins: 12,
    Fat: 6,
    Carbohydrates: 52,
    Calorie: 308,
  },
  {
    Name: "Хрен",
    Proteins: 3,
    Fat: 5,
    Carbohydrates: 14,
    Calorie: 113,
  },
  {
    Name: "Хурма",
    Proteins: 1,
    Fat: 0,
    Carbohydrates: 15,
    Calorie: 65,
  },
  {
    Name: "Цедра апельсина",
    Proteins: 1,
    Fat: 0,
    Carbohydrates: 6,
    Calorie: 36,
  },
  {
    Name: "Цедра лимона",
    Proteins: 1,
    Fat: 0,
    Carbohydrates: 4,
    Calorie: 28,
  },
  {
    Name: "Цукаты",
    Proteins: 3,
    Fat: 0,
    Carbohydrates: 56,
    Calorie: 224,
  },
  {
    Name: "Цукини",
    Proteins: 2,
    Fat: 0,
    Carbohydrates: 3,
    Calorie: 18,
  },
  {
    Name: "Черемша",
    Proteins: 2,
    Fat: 0,
    Carbohydrates: 7,
    Calorie: 37,
  },
  {
    Name: "Черешня",
    Proteins: 1,
    Fat: 0,
    Carbohydrates: 12,
    Calorie: 51,
  },
  {
    Name: "Черника",
    Proteins: 1,
    Fat: 0,
    Carbohydrates: 9,
    Calorie: 39,
  },
  {
    Name: "Чернослив (сухофрукты)",
    Proteins: 3,
    Fat: 0,
    Carbohydrates: 62,
    Calorie: 256,
  },
  {
    Name: "Чеснок",
    Proteins: 6,
    Fat: 0,
    Carbohydrates: 23,
    Calorie: 115,
  },
  {
    Name: "Чечевица зелёная",
    Proteins: 24,
    Fat: 2,
    Carbohydrates: 44,
    Calorie: 286,
  },
  {
    Name: "Чечевица красная",
    Proteins: 22,
    Fat: 1,
    Carbohydrates: 49,
    Calorie: 312,
  },
  {
    Name: "Шелковица",
    Proteins: 1,
    Fat: 0,
    Carbohydrates: 13,
    Calorie: 52,
  },
  {
    Name: "Шоколад горький 75%",
    Proteins: 9,
    Fat: 41,
    Carbohydrates: 39,
    Calorie: 550,
  },
  {
    Name: "Шоколад горький 80%",
    Proteins: 12,
    Fat: 39,
    Carbohydrates: 34,
    Calorie: 527,
  },
  {
    Name: "Шоколад молочный",
    Proteins: 7,
    Fat: 34,
    Carbohydrates: 52,
    Calorie: 539,
  },
  {
    Name: "Шпинат",
    Proteins: 3,
    Fat: 0,
    Carbohydrates: 2,
    Calorie: 22,
  },
  {
    Name: "Щавель",
    Proteins: 2,
    Fat: 0,
    Carbohydrates: 5,
    Calorie: 25,
  },
  {
    Name: "Яблоки",
    Proteins: 1,
    Fat: 1,
    Carbohydrates: 13,
    Calorie: 60,
  },
  {
    Name: "Яблоки сушёные (сухофрукты)",
    Proteins: 3,
    Fat: 0,
    Carbohydrates: 66,
    Calorie: 269,
  },
  {
    Name: "Яйца",
    Proteins: 15,
    Fat: 13,
    Carbohydrates: 1,
    Calorie: 162,
  },
  {
    Name: "",
    Proteins: null,
    Fat: null,
    Carbohydrates: null,
    Calorie: null,
  },
];
module.exports = ru_food;
